<!--
  ~ Atricore IDBus
  ~
  ~ Copyright 2009, Atricore Inc.
  ~
  ~ This is free software; you can redistribute it and/or modify it
  ~ under the terms of the GNU Lesser General Public License as
  ~ published by the Free Software Foundation; either version 2.1 of
  ~ the License, or (at your option) any later version.
  ~
  ~ This software is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
  ~ Lesser General Public License for more details.
  ~
  ~ You should have received a copy of the GNU Lesser General Public
  ~ License along with this software; if not, write to the Free
  ~ Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
  ~ 02110-1301 USA, or see the FSF site: http://www.fsf.org.
  -->

<wsdl:definitions
        name="SAML V1.1 Service"
        targetNamespace="urn:oasis:names:tc:SAML:1.0:wsdl"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        xmlns:tns="urn:oasis:names:tc:SAML:1.0:wsdl"
        xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
        xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
        xmlns:samlp="urn:oasis:names:tc:SAML:1.0:protocol"
        xmlns:saml="urn:oasis:names:tc:SAML:1.0:assertion"
        xmlns:ds="http://www.w3.org/2000/09/xmldsig#"
        xmlns="http://schemas.xmlsoap.org/wsdl/">

    <wsdl:types>
        <xsd:schema>
            <xsd:import namespace="urn:oasis:names:tc:SAML:1.0:protocol"
                        schemaLocation="saml-schema-idbus-1.1.xsd"/>
        </xsd:schema>

    </wsdl:types>

    <!-- protocol message definitions -->
    <wsdl:message name="SAMLRequestMessage">
        <wsdl:part name="body" element="samlp:Request"/>
    </wsdl:message>

    <wsdl:message name="SAMLResponseMessage">
        <wsdl:part name="body" element="samlp:Response"/>
    </wsdl:message>

    <wsdl:portType name="SAMLRequestPortType">

        <wsdl:operation name="SAMLRequest">
            <wsdl:input name="SAMLRequestInput"
                        message="tns:SAMLRequestMessage"/>
            <wsdl:output name="SAMLResponseOutput"
                         message="tns:SAMLResponseMessage"/>
        </wsdl:operation>

    </wsdl:portType>

    <wsdl:binding name="SAMLSoapBinding" type="tns:SAMLRequestPortType">
        <soap:binding style="document"
                      transport="http://schemas.xmlsoap.org/soap/http"/>

        <wsdl:operation name="SAMLRequest">
            <soap:operation style="document"
                            soapAction="http://www.oasis-open.org/committees/security"/>

            <wsdl:input name="SAMLRequestInput">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="SAMLResponseOutput">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>

    </wsdl:binding>

    <wsdl:service name="SAMLService">
        <documentation>SAML V1.1 Service</documentation>
        <port name="soap"
              binding="tns:SAMLSoapBinding">
            <soap:address location="http://localhost:8192/SAMLService/"/>
        </port>
    </wsdl:service>   


</wsdl:definitions>