package com.atricore.idbus.console.lifecycle.main.transform.transformers.domino;

import com.atricore.idbus.console.lifecycle.main.domain.IdentityAppliance;
import com.atricore.idbus.console.lifecycle.main.domain.metadata.*;
import com.atricore.idbus.console.lifecycle.main.exception.TransformException;
import com.atricore.idbus.console.lifecycle.main.transform.IdProjectModule;
import com.atricore.idbus.console.lifecycle.main.transform.IdProjectResource;
import com.atricore.idbus.console.lifecycle.main.transform.TransformEvent;
import com.atricore.idbus.console.lifecycle.main.transform.transformers.AbstractTransformer;
import com.atricore.idbus.console.lifecycle.support.springmetadata.model.Bean;
import com.atricore.idbus.console.lifecycle.support.springmetadata.model.Beans;
import com.atricore.idbus.console.lifecycle.support.springmetadata.model.Description;
import com.atricore.idbus.console.lifecycle.support.springmetadata.model.Entry;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.atricore.idbus.capabilities.sso.support.binding.SSOBinding;
import org.atricore.idbus.kernel.main.federation.metadata.CircleOfTrustImpl;
import org.atricore.idbus.kernel.main.federation.metadata.CircleOfTrustManagerImpl;
import org.atricore.idbus.kernel.main.mediation.binding.BindingChannelImpl;
import org.atricore.idbus.kernel.main.mediation.camel.component.logging.CamelLogMessageBuilder;
import org.atricore.idbus.kernel.main.mediation.camel.component.logging.HttpLogMessageBuilder;
import org.atricore.idbus.kernel.main.mediation.camel.logging.DefaultMediationLogger;
import org.atricore.idbus.kernel.main.mediation.endpoint.IdentityMediationEndpointImpl;
import org.atricore.idbus.kernel.main.mediation.osgi.OsgiIdentityMediationUnit;
import org.atricore.idbus.kernel.main.mediation.provider.BindingProviderImpl;

import java.util.*;

import static com.atricore.idbus.console.lifecycle.support.springmetadata.util.BeanUtils.*;

public class DominoBPTransformer extends AbstractTransformer {

    private static final Log logger = LogFactory.getLog(DominoBPTransformer.class);


    @Override
    public boolean accept(TransformEvent event) {
        return event.getData() instanceof DominoResource;
    }

    @Override
    public void before(TransformEvent event) throws TransformException {
        DominoResource dominoRes = (DominoResource) event.getData();

        InternalSaml2ServiceProvider sp = dominoRes.getServiceConnection().getSp();
        IdentityApplianceDefinition applianceDef = dominoRes.getServiceConnection().getSp().getIdentityAppliance();
        IdentityAppliance appliance = event.getContext().getProject().getIdAppliance();

        Date now = new Date();

        Beans bpBeans = new Beans();

        Description descr = new Description();
        descr.getContent().add(dominoRes.getName() + " : BP Configuration generated by Atricore Identity Bus Server on " + now.toGMTString());
        descr.getContent().add(dominoRes.getDescription());

        bpBeans.setDescription(descr);

        Beans baseBeans = (Beans) event.getContext().get("beans");

        // Publish root element so that other transformers can use it.
        event.getContext().put("bpBeans", bpBeans);

        if (logger.isDebugEnabled())
            logger.debug("Generating BP " + dominoRes.getName() + " configuration model");

        Bean bpBean = newBean(bpBeans, normalizeBeanName(dominoRes.getName()),
                BindingProviderImpl.class.getName());

        // Name
        setPropertyValue(bpBean, "name", bpBean.getName());

        // Role
        setPropertyValue(bpBean, "role", "{urn:org:atricore:idbus:domino:metadata}DominoLTPADescriptor");

        // unitContainer
        setPropertyRef(bpBean, "unitContainer", applianceDef.getName() + "-container");

        // COT Manager
        Collection<Bean> cotMgrs = getBeansOfType(baseBeans, CircleOfTrustManagerImpl.class.getName());
        if (cotMgrs.size() == 1) {
            Bean cotMgr = cotMgrs.iterator().next();
            setPropertyRef(bpBean, "cotManager", cotMgr.getName());
        }

        // State Manager
        setPropertyRef(bpBean, "stateManager", applianceDef.getName() + "-state-manager");

        // MBean
        Bean mBean = newBean(bpBeans, bpBean.getName() + "-mbean",
                "org.atricore.idbus.capabilities.sso.management.internal.BindingProviderMBeanImpl");
        setPropertyRef(mBean, "bindingProvider", bpBean.getName());

        // MBean Exporter
        Bean mBeanExporter = newBean(bpBeans, bpBean.getName() + "-mbean-exporter", "org.springframework.jmx.export.MBeanExporter");
        setPropertyRef(mBeanExporter, "server", "mBeanServer");

        Bean mBeanEntryKeyBean = newBean(bpBeans, mBean.getName() + "-key", String.class);
        setConstructorArg(mBeanEntryKeyBean, 0, "java.lang.String", appliance.getNamespace() + "." +
                event.getContext().getCurrentModule().getId() + ":type=BindingProvider,name=" + applianceDef.getName() + "." + bpBean.getName());

        Entry mBeanEntry = new Entry();
        mBeanEntry.setKeyRef(mBeanEntryKeyBean.getName());
        mBeanEntry.setValueRef(mBean.getName());

        addEntryToMap(mBeanExporter, "beans", mBeanEntry);

        // Domino Binding Channel
        Bean bc = newBean(bpBeans, normalizeBeanName(dominoRes.getName()) + "-domino-binding-channel",
                "org.atricore.idbus.kernel.main.mediation.binding.BindingChannelImpl");
        setPropertyValue(bc, "name", bc.getName());
        setPropertyValue(bc, "description", dominoRes.getDescription());
        setPropertyRef(bc, "federatedProvider", bpBean.getName());
        setPropertyRef(bc, "unitContainer", applianceDef.getName() + "-container");

        String locationPath = resolveLocationPath(applianceDef.getLocation()) + "/" + dominoRes.getName().toUpperCase();
        String location = resolveLocationBaseUrl(applianceDef.getLocation()) + locationPath;

        setPropertyValue(bc, "location", location);

        setPropertyRef(bc, "unitContainer", applianceDef.getName() + "-container");
        setPropertyRef(bc, "identityMediator", bpBean.getName() + "-binding-mediator");

        // endpoints
        List<Bean> endpoints = new ArrayList<Bean>();

        Bean acsArtifact = newAnonymousBean(IdentityMediationEndpointImpl.class);
        acsArtifact.setName(bpBean.getName() + "-binding-ssop-acs-artifact");
        setPropertyValue(acsArtifact, "name", acsArtifact.getName());
        setPropertyValue(acsArtifact, "type", "{urn:org:atricore:idbus:domino:metadata}AssertionConsumerService");
        setPropertyValue(acsArtifact, "binding", SSOBinding.SSO_ARTIFACT.getValue());
        setPropertyValue(acsArtifact, "location", "/SSO/ACS/ARTIFACT");
        endpoints.add(acsArtifact);

        Bean ssoRedirect = newAnonymousBean(IdentityMediationEndpointImpl.class);
        ssoRedirect.setName(bpBean.getName() + "-binding-ssop-sso-redir");
        setPropertyValue(ssoRedirect, "name", ssoRedirect.getName());
        setPropertyValue(ssoRedirect, "type", "{urn:org:atricore:idbus:domino:metadata}OutboundSSOService");
        setPropertyValue(ssoRedirect, "binding", SSOBinding.SSO_REDIRECT.getValue());
        setPropertyValue(ssoRedirect, "location", "/SSO/SSO/REDIR");
        endpoints.add(ssoRedirect);

        setPropertyAsBeans(bc, "endpoints", endpoints);

        setPropertyRef(bpBean, "bindingChannel", bc.getName());


        // binding-mediator
        Bean bindingMediator = newBean(bpBeans, bpBean.getName() + "-binding-mediator", "org.atricore.idbus.capabilities.domino.main.DominoOutboundSSOMediator");
        setPropertyValue(bindingMediator, "logMessages", true);
        setPropertyBean(bindingMediator, "bindingFactory", newAnonymousBean("org.atricore.idbus.capabilities.domino.main.DominoBindingFactory"));

        // artifactQueueManager
        // setPropertyRef(bindingMediator, "artifactQueueManager", applianceDef.getName() + "-aqm");
        setPropertyRef(bindingMediator, "artifactQueueManager", "artifactQueueManager");

        // errorUrl
        setPropertyValue(bindingMediator, "errorUrl", resolveUiErrorLocation(appliance));

        // warningUrl
        setPropertyValue(bindingMediator, "warningUrl", resolveUiWarningLocation(appliance));

        // SAML2 SP Alias (preferred/default idp channel)
        IdentityProviderChannel preferredIdpChannel = null;
        for (FederatedConnection fc : sp.getFederatedConnectionsA()) {
            IdentityProviderChannel idpc = (IdentityProviderChannel) fc.getChannelA();
            if (idpc.isPreferred()) {
                preferredIdpChannel = idpc;
                break;
            }
        }

        if (preferredIdpChannel == null) {
            for (FederatedConnection fc : sp.getFederatedConnectionsB()) {
                IdentityProviderChannel idpc = (IdentityProviderChannel) fc.getChannelB();
                if (idpc.isPreferred()) {
                    preferredIdpChannel = idpc;
                    break;
                }
            }
        }

        String spAlias = resolveLocationUrl(sp, preferredIdpChannel) + "/SAML2/MD";
        setPropertyValue(bindingMediator, "spAlias", spAlias);

        // logger
        List<Bean> bpLogBuilders = new ArrayList<Bean>();
        bpLogBuilders.add(newAnonymousBean(CamelLogMessageBuilder.class));
        bpLogBuilders.add(newAnonymousBean(HttpLogMessageBuilder.class));

        Bean bpLogger = newAnonymousBean(DefaultMediationLogger.class.getName());
        bpLogger.setName(bpBean.getName() + "-mediation-logger");
        setPropertyValue(bpLogger, "category", appliance.getNamespace() + ".wire." + bpBean.getName());
        setPropertyAsBeans(bpLogger, "messageBuilders", bpLogBuilders);
        setPropertyBean(bindingMediator, "logger", bpLogger);

        setPropertyValue(bindingMediator, "serverUrl", dominoRes.getServerUrl());
        setPropertyValue(bindingMediator, "homeLocation", dominoRes.getHomeLocation().toString());

    }

    @Override
    public Object after(TransformEvent event) throws TransformException {
        IdProjectModule module = event.getContext().getCurrentModule();
        Beans baseBeans = (Beans) event.getContext().get("beans");
        Beans bpBeans = (Beans) event.getContext().get("bpBeans");

        Bean bpBean = getBeansOfType(bpBeans, BindingProviderImpl.class.getName()).iterator().next();

        if (logger.isDebugEnabled())
            logger.debug("Wiring BP Provider/Channel with mediation components ("+bpBean.getName()+")");

        // Wire provider to COT
        Collection<Bean> cots = getBeansOfType(baseBeans, CircleOfTrustImpl.class.getName());
        if (cots.size() == 1) {
            Bean cot = cots.iterator().next();
            addPropertyBeansAsRefsToSet(cot, "providers", bpBean);
        }

        // Mediation Unit for binding channel
        Collection<Bean> mus = getBeansOfType(baseBeans, OsgiIdentityMediationUnit.class.getName());
        if (mus.size() == 1) {
            Bean mu = mus.iterator().next();
            Collection<Bean> bindingChannels = getBeansOfType(bpBeans, BindingChannelImpl.class.getName());
            for (Bean b : bindingChannels) {
                addPropertyBeansAsRefs(mu, "channels", b);
            }
        } else {
            throw new TransformException("One and only one Identity Mediation Unit is expected, found " + mus.size());
        }

        IdProjectResource<Beans> rBeans =  new IdProjectResource<Beans>(idGen.generateId(),
                bpBean.getName(),
                bpBean.getName(),
                "spring-beans",
                bpBeans);

        rBeans.setClassifier("jaxb");

        module.addResource(rBeans);

        return rBeans;

    }

}
